/**
 * @fileoverview gRPC-Web generated client stub for gossip
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.2
// source: gossip/message.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var peer_collection_pb = require('../peer/collection_pb.js')
const proto = {};
proto.gossip = require('./message_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gossip.GossipClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gossip.GossipPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gossip.Empty,
 *   !proto.gossip.Empty>}
 */
const methodDescriptor_Gossip_Ping = new grpc.web.MethodDescriptor(
  '/gossip.Gossip/Ping',
  grpc.web.MethodType.UNARY,
  proto.gossip.Empty,
  proto.gossip.Empty,
  /**
   * @param {!proto.gossip.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gossip.Empty.deserializeBinary
);


/**
 * @param {!proto.gossip.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gossip.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gossip.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gossip.GossipClient.prototype.ping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gossip.Gossip/Ping',
      request,
      metadata || {},
      methodDescriptor_Gossip_Ping,
      callback);
};


/**
 * @param {!proto.gossip.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gossip.Empty>}
 *     Promise that resolves to the response
 */
proto.gossip.GossipPromiseClient.prototype.ping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gossip.Gossip/Ping',
      request,
      metadata || {},
      methodDescriptor_Gossip_Ping);
};


module.exports = proto.gossip;

